name: update-tap
on:
  schedule:
    # Run every hour
    - cron:  '0 * * * *'

jobs:
  update-tap:
    if: false  # disable for now (needs personal access token)
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tap: c6o/homebrew-tools
          force: false
          livecheck: true
